service: sls-amazing-api

frameworkVersion: '>=1.1.0 <= 2.2.0'

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  region: eu-west-2

  environment:
    GOOGLE_MAPS_API_KEY: key9595

functions:
  endpointGet:
    handler: handler.endpointGet
    events:
      - http:
          path: get-endpoint
          method: GET
  endpointPost:
    handler: handler.endpointPost
    events:
      - http:
          path: post-endpoint
          method: POST
  envVariables:
    handler: envVariables.handler
    events:
      - http:
          path: envVariables
          method: GET
    environment:
      OTHER_API_KEY:
resources:
  Resources:
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-uploads

    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-users
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
